apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-web
  namespace: production
spec:
  type: NodePort
  ports:
   - protocol: TCP
     targetPort: 8080
     port: 80
     nodePort: 30008
  selector:
    app: web
