apiVersion: v1
kind: Pod
metadata: 
  name: mysql-volume
spec:
  containers:
   - name:  mysql
     image: mysql
     env:
      - name: MYSQL_DATABASE
        value: eazytraining
      - name: MYSQL_USER
        value: eazy
      - name: MYSQL_PASSWORD
        value: eazy
      - name: MYSQL_ROOT_PASSWORD
        value: password
     volumeMounts:
       - mountPath: /var/lib/mysql
         name: mysql-data
  volumes:
    - name: mysql-data
      hostPath:
        path: /data-volume
        type: Directory
