apiVersion: v1
kind: Service
metadata:
  name: service-clusterip-mysql
  namespace: wordpress-mysql
spec:
  type: ClusterIP
  ports:
   - protocol: TCP
     targetPort: 3306
     port: 3306
  selector:
    app: wordpress-db 
