apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-wordpress
  namespace: wordpress-mysql
spec:
  type: NodePort
  ports:
   - protocol: TCP
     targetPort: 80
     port: 80
     nodePort: 30008
  selector:
    app: wordpress-front
