apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color-pod
  labels: 
    app: webapp
spec:
  containers:
  -  name: webapp-color
     image: imazenka/app-color:latest
     ports:
       - containerPort: 8080
     env:
      - name: APP_COLOR
        value: red

